### ISSUE TITLE
Prnting the result of o2m2 resulst in an error

### ISSUE THREAD

**Issue by krassowski** [selbouhaddani/OmicsPLS#12]
Code:

```
r = o2m2(as.matrix(X), as.matrix(Y), 2, 0, 0) # works fine
print(r) # error
```

Error:
> Error in if (x$flags$stripped) cat("O2PLS fit: Stripped \n") else if (x$flags$highd) cat("O2PLS fit: High dimensional \n") else cat("O2PLS fit \n") : 
>   argument is of length zero
> Calls: <Anonymous> -> <Anonymous> -> withVisible -> print -> print.o2m

But using:

```
r = o2m(as.matrix(X), as.matrix(Y), 2, 0, 0, p_thresh=0)
print(r)
```

works fine.

**Comment by selbouhaddani** [comment]
I added a new class pre.o2m and corresponding print function for o2m2 etc. Now printing should not give an error (but the print itself is not informative). I encourage general users to use o2m, since all generics are written for class o2m.

Now there seems to be another issue, that these o2m2 etc are not being set to internal (they should). Will look into this later.

**Comment by krassowski** [comment]
Thank you!
